/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  ActivityReply: {
    text: {},
  },
  Character: {
    description: {},
    media: {
      sort: "MediaSort",
      type: "MediaType",
    },
  },
  CharacterEdge: {
    voiceActorRoles: {
      language: "StaffLanguage",
      sort: "StaffSort",
    },
    voiceActors: {
      language: "StaffLanguage",
      sort: "StaffSort",
    },
  },
  Favourites: {
    anime: {},
    characters: {},
    manga: {},
    staff: {},
    studios: {},
  },
  InternalPage: {
    activities: {
      sort: "ActivitySort",
      type: "ActivityType",
      type_in: "ActivityType",
      type_not: "ActivityType",
      type_not_in: "ActivityType",
    },
    activityReplies: {},
    airingSchedules: {
      sort: "AiringSort",
    },
    characterSubmissions: {
      sort: "SubmissionSort",
      status: "SubmissionStatus",
    },
    characters: {
      sort: "CharacterSort",
    },
    followers: {
      sort: "UserSort",
    },
    following: {
      sort: "UserSort",
    },
    likes: {
      type: "LikeableType",
    },
    media: {
      countryOfOrigin: "CountryCode",
      endDate: "FuzzyDateInt",
      endDate_greater: "FuzzyDateInt",
      endDate_lesser: "FuzzyDateInt",
      format: "MediaFormat",
      format_in: "MediaFormat",
      format_not: "MediaFormat",
      format_not_in: "MediaFormat",
      season: "MediaSeason",
      sort: "MediaSort",
      source: "MediaSource",
      source_in: "MediaSource",
      startDate: "FuzzyDateInt",
      startDate_greater: "FuzzyDateInt",
      startDate_lesser: "FuzzyDateInt",
      status: "MediaStatus",
      status_in: "MediaStatus",
      status_not: "MediaStatus",
      status_not_in: "MediaStatus",
      type: "MediaType",
    },
    mediaList: {
      completedAt: "FuzzyDateInt",
      completedAt_greater: "FuzzyDateInt",
      completedAt_lesser: "FuzzyDateInt",
      sort: "MediaListSort",
      startedAt: "FuzzyDateInt",
      startedAt_greater: "FuzzyDateInt",
      startedAt_lesser: "FuzzyDateInt",
      status: "MediaListStatus",
      status_in: "MediaListStatus",
      status_not: "MediaListStatus",
      status_not_in: "MediaListStatus",
      type: "MediaType",
    },
    mediaSubmissions: {
      sort: "SubmissionSort",
      status: "SubmissionStatus",
      type: "MediaType",
    },
    mediaTrends: {
      sort: "MediaTrendSort",
    },
    modActions: {},
    notifications: {
      type: "NotificationType",
      type_in: "NotificationType",
    },
    recommendations: {
      sort: "RecommendationSort",
    },
    reports: {},
    reviews: {
      mediaType: "MediaType",
      sort: "ReviewSort",
    },
    revisionHistory: {},
    staff: {
      sort: "StaffSort",
    },
    staffSubmissions: {
      sort: "SubmissionSort",
      status: "SubmissionStatus",
    },
    studios: {
      sort: "StudioSort",
    },
    threadComments: {
      sort: "ThreadCommentSort",
    },
    threads: {
      sort: "ThreadSort",
    },
    userBlockSearch: {},
    users: {
      sort: "UserSort",
    },
  },
  Media: {
    airingSchedule: {},
    characters: {
      role: "CharacterRole",
      sort: "CharacterSort",
    },
    description: {},
    recommendations: {
      sort: "RecommendationSort",
    },
    reviews: {
      sort: "ReviewSort",
    },
    source: {},
    staff: {
      sort: "StaffSort",
    },
    status: {},
    studios: {
      sort: "StudioSort",
    },
    trends: {
      sort: "MediaTrendSort",
    },
  },
  MediaEdge: {
    relationType: {},
    voiceActorRoles: {
      language: "StaffLanguage",
      sort: "StaffSort",
    },
    voiceActors: {
      language: "StaffLanguage",
      sort: "StaffSort",
    },
  },
  MediaList: {
    customLists: {},
    score: {
      format: "ScoreFormat",
    },
  },
  MediaListCollection: {
    customLists: {},
    statusLists: {},
  },
  MediaTitle: {
    english: {},
    native: {},
    romaji: {},
  },
  MessageActivity: {
    message: {},
  },
  Mutation: {
    DeleteActivity: {},
    DeleteActivityReply: {},
    DeleteCustomList: {
      type: "MediaType",
    },
    DeleteMediaListEntry: {},
    DeleteReview: {},
    DeleteThread: {},
    DeleteThreadComment: {},
    RateReview: {
      rating: "ReviewRating",
    },
    SaveActivityReply: {},
    SaveListActivity: {},
    SaveMediaListEntry: {
      completedAt: "FuzzyDateInput",
      startedAt: "FuzzyDateInput",
      status: "MediaListStatus",
    },
    SaveMessageActivity: {},
    SaveRecommendation: {
      rating: "RecommendationRating",
    },
    SaveReview: {},
    SaveTextActivity: {},
    SaveThread: {},
    SaveThreadComment: {},
    ToggleActivityPin: {},
    ToggleActivitySubscription: {},
    ToggleFavourite: {},
    ToggleFollow: {},
    ToggleLike: {
      type: "LikeableType",
    },
    ToggleLikeV2: {
      type: "LikeableType",
    },
    ToggleThreadSubscription: {},
    UpdateAniChartHighlights: {
      highlights: "AniChartHighlightInput",
    },
    UpdateAniChartSettings: {},
    UpdateFavouriteOrder: {},
    UpdateMediaListEntries: {
      completedAt: "FuzzyDateInput",
      startedAt: "FuzzyDateInput",
      status: "MediaListStatus",
    },
    UpdateUser: {
      animeListOptions: "MediaListOptionsInput",
      disabledListActivity: "ListActivityOptionInput",
      mangaListOptions: "MediaListOptionsInput",
      notificationOptions: "NotificationOptionInput",
      scoreFormat: "ScoreFormat",
      staffNameLanguage: "UserStaffNameLanguage",
      titleLanguage: "UserTitleLanguage",
    },
  },
  Page: {
    activities: {
      sort: "ActivitySort",
      type: "ActivityType",
      type_in: "ActivityType",
      type_not: "ActivityType",
      type_not_in: "ActivityType",
    },
    activityReplies: {},
    airingSchedules: {
      sort: "AiringSort",
    },
    characters: {
      sort: "CharacterSort",
    },
    followers: {
      sort: "UserSort",
    },
    following: {
      sort: "UserSort",
    },
    likes: {
      type: "LikeableType",
    },
    media: {
      countryOfOrigin: "CountryCode",
      endDate: "FuzzyDateInt",
      endDate_greater: "FuzzyDateInt",
      endDate_lesser: "FuzzyDateInt",
      format: "MediaFormat",
      format_in: "MediaFormat",
      format_not: "MediaFormat",
      format_not_in: "MediaFormat",
      season: "MediaSeason",
      sort: "MediaSort",
      source: "MediaSource",
      source_in: "MediaSource",
      startDate: "FuzzyDateInt",
      startDate_greater: "FuzzyDateInt",
      startDate_lesser: "FuzzyDateInt",
      status: "MediaStatus",
      status_in: "MediaStatus",
      status_not: "MediaStatus",
      status_not_in: "MediaStatus",
      type: "MediaType",
    },
    mediaList: {
      completedAt: "FuzzyDateInt",
      completedAt_greater: "FuzzyDateInt",
      completedAt_lesser: "FuzzyDateInt",
      sort: "MediaListSort",
      startedAt: "FuzzyDateInt",
      startedAt_greater: "FuzzyDateInt",
      startedAt_lesser: "FuzzyDateInt",
      status: "MediaListStatus",
      status_in: "MediaListStatus",
      status_not: "MediaListStatus",
      status_not_in: "MediaListStatus",
      type: "MediaType",
    },
    mediaTrends: {
      sort: "MediaTrendSort",
    },
    notifications: {
      type: "NotificationType",
      type_in: "NotificationType",
    },
    recommendations: {
      sort: "RecommendationSort",
    },
    reviews: {
      mediaType: "MediaType",
      sort: "ReviewSort",
    },
    staff: {
      sort: "StaffSort",
    },
    studios: {
      sort: "StudioSort",
    },
    threadComments: {
      sort: "ThreadCommentSort",
    },
    threads: {
      sort: "ThreadSort",
    },
    users: {
      sort: "UserSort",
    },
  },
  Query: {
    Activity: {
      sort: "ActivitySort",
      type: "ActivityType",
      type_in: "ActivityType",
      type_not: "ActivityType",
      type_not_in: "ActivityType",
    },
    ActivityReply: {},
    AiringSchedule: {
      sort: "AiringSort",
    },
    Character: {
      sort: "CharacterSort",
    },
    ExternalLinkSourceCollection: {
      mediaType: "ExternalLinkMediaType",
      type: "ExternalLinkType",
    },
    Follower: {
      sort: "UserSort",
    },
    Following: {
      sort: "UserSort",
    },
    Like: {
      type: "LikeableType",
    },
    Markdown: {},
    Media: {
      countryOfOrigin: "CountryCode",
      endDate: "FuzzyDateInt",
      endDate_greater: "FuzzyDateInt",
      endDate_lesser: "FuzzyDateInt",
      format: "MediaFormat",
      format_in: "MediaFormat",
      format_not: "MediaFormat",
      format_not_in: "MediaFormat",
      season: "MediaSeason",
      sort: "MediaSort",
      source: "MediaSource",
      source_in: "MediaSource",
      startDate: "FuzzyDateInt",
      startDate_greater: "FuzzyDateInt",
      startDate_lesser: "FuzzyDateInt",
      status: "MediaStatus",
      status_in: "MediaStatus",
      status_not: "MediaStatus",
      status_not_in: "MediaStatus",
      type: "MediaType",
    },
    MediaList: {
      completedAt: "FuzzyDateInt",
      completedAt_greater: "FuzzyDateInt",
      completedAt_lesser: "FuzzyDateInt",
      sort: "MediaListSort",
      startedAt: "FuzzyDateInt",
      startedAt_greater: "FuzzyDateInt",
      startedAt_lesser: "FuzzyDateInt",
      status: "MediaListStatus",
      status_in: "MediaListStatus",
      status_not: "MediaListStatus",
      status_not_in: "MediaListStatus",
      type: "MediaType",
    },
    MediaListCollection: {
      completedAt: "FuzzyDateInt",
      completedAt_greater: "FuzzyDateInt",
      completedAt_lesser: "FuzzyDateInt",
      sort: "MediaListSort",
      startedAt: "FuzzyDateInt",
      startedAt_greater: "FuzzyDateInt",
      startedAt_lesser: "FuzzyDateInt",
      status: "MediaListStatus",
      status_in: "MediaListStatus",
      status_not: "MediaListStatus",
      status_not_in: "MediaListStatus",
      type: "MediaType",
    },
    MediaTagCollection: {},
    MediaTrend: {
      sort: "MediaTrendSort",
    },
    Notification: {
      type: "NotificationType",
      type_in: "NotificationType",
    },
    Page: {},
    Recommendation: {
      sort: "RecommendationSort",
    },
    Review: {
      mediaType: "MediaType",
      sort: "ReviewSort",
    },
    Staff: {
      sort: "StaffSort",
    },
    Studio: {
      sort: "StudioSort",
    },
    Thread: {
      sort: "ThreadSort",
    },
    ThreadComment: {
      sort: "ThreadCommentSort",
    },
    User: {
      sort: "UserSort",
    },
  },
  Review: {
    body: {},
  },
  SiteStatistics: {
    anime: {
      sort: "SiteTrendSort",
    },
    characters: {
      sort: "SiteTrendSort",
    },
    manga: {
      sort: "SiteTrendSort",
    },
    reviews: {
      sort: "SiteTrendSort",
    },
    staff: {
      sort: "SiteTrendSort",
    },
    studios: {
      sort: "SiteTrendSort",
    },
    users: {
      sort: "SiteTrendSort",
    },
  },
  Staff: {
    characterMedia: {
      sort: "MediaSort",
    },
    characters: {
      sort: "CharacterSort",
    },
    description: {},
    staffMedia: {
      sort: "MediaSort",
      type: "MediaType",
    },
  },
  Studio: {
    media: {
      sort: "MediaSort",
    },
  },
  TextActivity: {
    text: {},
  },
  Thread: {
    body: {},
  },
  ThreadComment: {
    comment: {},
  },
  User: {
    about: {},
    favourites: {},
  },
  UserStatistics: {
    countries: {
      sort: "UserStatisticsSort",
    },
    formats: {
      sort: "UserStatisticsSort",
    },
    genres: {
      sort: "UserStatisticsSort",
    },
    lengths: {
      sort: "UserStatisticsSort",
    },
    releaseYears: {
      sort: "UserStatisticsSort",
    },
    scores: {
      sort: "UserStatisticsSort",
    },
    staff: {
      sort: "UserStatisticsSort",
    },
    startYears: {
      sort: "UserStatisticsSort",
    },
    statuses: {
      sort: "UserStatisticsSort",
    },
    studios: {
      sort: "UserStatisticsSort",
    },
    tags: {
      sort: "UserStatisticsSort",
    },
    voiceActors: {
      sort: "UserStatisticsSort",
    },
  },
  ActivitySort: "enum" as const,
  ActivityType: "enum" as const,
  AiringSort: "enum" as const,
  CharacterRole: "enum" as const,
  CharacterSort: "enum" as const,
  ExternalLinkMediaType: "enum" as const,
  ExternalLinkType: "enum" as const,
  LikeableType: "enum" as const,
  MediaFormat: "enum" as const,
  MediaListSort: "enum" as const,
  MediaListStatus: "enum" as const,
  MediaRankType: "enum" as const,
  MediaRelation: "enum" as const,
  MediaSeason: "enum" as const,
  MediaSort: "enum" as const,
  MediaSource: "enum" as const,
  MediaStatus: "enum" as const,
  MediaTrendSort: "enum" as const,
  MediaType: "enum" as const,
  ModActionType: "enum" as const,
  ModRole: "enum" as const,
  NotificationType: "enum" as const,
  RecommendationRating: "enum" as const,
  RecommendationSort: "enum" as const,
  ReviewRating: "enum" as const,
  ReviewSort: "enum" as const,
  RevisionHistoryAction: "enum" as const,
  ScoreFormat: "enum" as const,
  SiteTrendSort: "enum" as const,
  StaffLanguage: "enum" as const,
  StaffSort: "enum" as const,
  StudioSort: "enum" as const,
  SubmissionSort: "enum" as const,
  SubmissionStatus: "enum" as const,
  ThreadCommentSort: "enum" as const,
  ThreadSort: "enum" as const,
  UserSort: "enum" as const,
  UserStaffNameLanguage: "enum" as const,
  UserStatisticsSort: "enum" as const,
  UserTitleLanguage: "enum" as const,
  CountryCode: `scalar.CountryCode` as const,
  FuzzyDateInt: `scalar.FuzzyDateInt` as const,
  Json: `scalar.Json` as const,
  AiringScheduleInput: {},
  AniChartHighlightInput: {},
  CharacterNameInput: {},
  FuzzyDateInput: {},
  ListActivityOptionInput: {
    type: "MediaListStatus",
  },
  MediaExternalLinkInput: {},
  MediaListOptionsInput: {},
  MediaTitleInput: {},
  NotificationOptionInput: {
    type: "NotificationType",
  },
  StaffNameInput: {},
  ID: `scalar.ID` as const,
};

export const ReturnTypes: Record<string, any> = {
  ActivityUnion: {
    "...on ListActivity": "ListActivity",
    "...on MessageActivity": "MessageActivity",
    "...on TextActivity": "TextActivity",
  },
  LikeableUnion: {
    "...on ActivityReply": "ActivityReply",
    "...on ListActivity": "ListActivity",
    "...on MessageActivity": "MessageActivity",
    "...on TextActivity": "TextActivity",
    "...on Thread": "Thread",
    "...on ThreadComment": "ThreadComment",
  },
  NotificationUnion: {
    "...on ActivityLikeNotification": "ActivityLikeNotification",
    "...on ActivityMentionNotification": "ActivityMentionNotification",
    "...on ActivityMessageNotification": "ActivityMessageNotification",
    "...on ActivityReplyLikeNotification": "ActivityReplyLikeNotification",
    "...on ActivityReplyNotification": "ActivityReplyNotification",
    "...on ActivityReplySubscribedNotification":
      "ActivityReplySubscribedNotification",
    "...on AiringNotification": "AiringNotification",
    "...on FollowingNotification": "FollowingNotification",
    "...on MediaDataChangeNotification": "MediaDataChangeNotification",
    "...on MediaDeletionNotification": "MediaDeletionNotification",
    "...on MediaMergeNotification": "MediaMergeNotification",
    "...on RelatedMediaAdditionNotification":
      "RelatedMediaAdditionNotification",
    "...on ThreadCommentLikeNotification": "ThreadCommentLikeNotification",
    "...on ThreadCommentMentionNotification":
      "ThreadCommentMentionNotification",
    "...on ThreadCommentReplyNotification": "ThreadCommentReplyNotification",
    "...on ThreadCommentSubscribedNotification":
      "ThreadCommentSubscribedNotification",
    "...on ThreadLikeNotification": "ThreadLikeNotification",
  },
  ActivityLikeNotification: {
    activity: "ActivityUnion",
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ActivityMentionNotification: {
    activity: "ActivityUnion",
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ActivityMessageNotification: {
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    message: "MessageActivity",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ActivityReply: {
    activityId: "Int",
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    likeCount: "Int",
    likes: "User",
    text: "String",
    user: "User",
    userId: "Int",
  },
  ActivityReplyLikeNotification: {
    activity: "ActivityUnion",
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ActivityReplyNotification: {
    activity: "ActivityUnion",
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ActivityReplySubscribedNotification: {
    activity: "ActivityUnion",
    activityId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  AiringNotification: {
    animeId: "Int",
    contexts: "String",
    createdAt: "Int",
    episode: "Int",
    id: "Int",
    media: "Media",
    type: "NotificationType",
  },
  AiringProgression: {
    episode: "Float",
    score: "Float",
    watching: "Int",
  },
  AiringSchedule: {
    airingAt: "Int",
    episode: "Int",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    timeUntilAiring: "Int",
  },
  AiringScheduleConnection: {
    edges: "AiringScheduleEdge",
    nodes: "AiringSchedule",
    pageInfo: "PageInfo",
  },
  AiringScheduleEdge: {
    id: "Int",
    node: "AiringSchedule",
  },
  AniChartUser: {
    highlights: "Json",
    settings: "Json",
    user: "User",
  },
  Character: {
    age: "String",
    bloodType: "String",
    dateOfBirth: "FuzzyDate",
    description: "String",
    favourites: "Int",
    gender: "String",
    id: "Int",
    image: "CharacterImage",
    isFavourite: "Boolean",
    isFavouriteBlocked: "Boolean",
    media: "MediaConnection",
    modNotes: "String",
    name: "CharacterName",
    siteUrl: "String",
    updatedAt: "Int",
  },
  CharacterConnection: {
    edges: "CharacterEdge",
    nodes: "Character",
    pageInfo: "PageInfo",
  },
  CharacterEdge: {
    favouriteOrder: "Int",
    id: "Int",
    media: "Media",
    name: "String",
    node: "Character",
    role: "CharacterRole",
    voiceActorRoles: "StaffRoleType",
    voiceActors: "Staff",
  },
  CharacterImage: {
    large: "String",
    medium: "String",
  },
  CharacterName: {
    alternative: "String",
    alternativeSpoiler: "String",
    first: "String",
    full: "String",
    last: "String",
    middle: "String",
    native: "String",
    userPreferred: "String",
  },
  CharacterSubmission: {
    assignee: "User",
    character: "Character",
    createdAt: "Int",
    id: "Int",
    locked: "Boolean",
    notes: "String",
    source: "String",
    status: "SubmissionStatus",
    submission: "Character",
    submitter: "User",
  },
  CharacterSubmissionConnection: {
    edges: "CharacterSubmissionEdge",
    nodes: "CharacterSubmission",
    pageInfo: "PageInfo",
  },
  CharacterSubmissionEdge: {
    node: "CharacterSubmission",
    role: "CharacterRole",
    submittedVoiceActors: "StaffSubmission",
    voiceActors: "Staff",
  },
  Deleted: {
    deleted: "Boolean",
  },
  Favourites: {
    anime: "MediaConnection",
    characters: "CharacterConnection",
    manga: "MediaConnection",
    staff: "StaffConnection",
    studios: "StudioConnection",
  },
  FollowingNotification: {
    context: "String",
    createdAt: "Int",
    id: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  FormatStats: {
    amount: "Int",
    format: "MediaFormat",
  },
  FuzzyDate: {
    day: "Int",
    month: "Int",
    year: "Int",
  },
  GenreStats: {
    amount: "Int",
    genre: "String",
    meanScore: "Int",
    timeWatched: "Int",
  },
  InternalPage: {
    activities: "ActivityUnion",
    activityReplies: "ActivityReply",
    airingSchedules: "AiringSchedule",
    characterSubmissions: "CharacterSubmission",
    characters: "Character",
    followers: "User",
    following: "User",
    likes: "User",
    media: "Media",
    mediaList: "MediaList",
    mediaSubmissions: "MediaSubmission",
    mediaTrends: "MediaTrend",
    modActions: "ModAction",
    notifications: "NotificationUnion",
    pageInfo: "PageInfo",
    recommendations: "Recommendation",
    reports: "Report",
    reviews: "Review",
    revisionHistory: "RevisionHistory",
    staff: "Staff",
    staffSubmissions: "StaffSubmission",
    studios: "Studio",
    threadComments: "ThreadComment",
    threads: "Thread",
    userBlockSearch: "User",
    users: "User",
  },
  ListActivity: {
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    isLocked: "Boolean",
    isPinned: "Boolean",
    isSubscribed: "Boolean",
    likeCount: "Int",
    likes: "User",
    media: "Media",
    progress: "String",
    replies: "ActivityReply",
    replyCount: "Int",
    siteUrl: "String",
    status: "String",
    type: "ActivityType",
    user: "User",
    userId: "Int",
  },
  ListActivityOption: {
    disabled: "Boolean",
    type: "MediaListStatus",
  },
  ListScoreStats: {
    meanScore: "Int",
    standardDeviation: "Int",
  },
  Media: {
    airingSchedule: "AiringScheduleConnection",
    autoCreateForumThread: "Boolean",
    averageScore: "Int",
    bannerImage: "String",
    chapters: "Int",
    characters: "CharacterConnection",
    countryOfOrigin: "CountryCode",
    coverImage: "MediaCoverImage",
    description: "String",
    duration: "Int",
    endDate: "FuzzyDate",
    episodes: "Int",
    externalLinks: "MediaExternalLink",
    favourites: "Int",
    format: "MediaFormat",
    genres: "String",
    hashtag: "String",
    id: "Int",
    idMal: "Int",
    isAdult: "Boolean",
    isFavourite: "Boolean",
    isFavouriteBlocked: "Boolean",
    isLicensed: "Boolean",
    isLocked: "Boolean",
    isRecommendationBlocked: "Boolean",
    isReviewBlocked: "Boolean",
    meanScore: "Int",
    mediaListEntry: "MediaList",
    modNotes: "String",
    nextAiringEpisode: "AiringSchedule",
    popularity: "Int",
    rankings: "MediaRank",
    recommendations: "RecommendationConnection",
    relations: "MediaConnection",
    reviews: "ReviewConnection",
    season: "MediaSeason",
    seasonInt: "Int",
    seasonYear: "Int",
    siteUrl: "String",
    source: "MediaSource",
    staff: "StaffConnection",
    startDate: "FuzzyDate",
    stats: "MediaStats",
    status: "MediaStatus",
    streamingEpisodes: "MediaStreamingEpisode",
    studios: "StudioConnection",
    synonyms: "String",
    tags: "MediaTag",
    title: "MediaTitle",
    trailer: "MediaTrailer",
    trending: "Int",
    trends: "MediaTrendConnection",
    type: "MediaType",
    updatedAt: "Int",
    volumes: "Int",
  },
  MediaCharacter: {
    character: "Character",
    characterName: "String",
    dubGroup: "String",
    id: "Int",
    role: "CharacterRole",
    roleNotes: "String",
    voiceActor: "Staff",
  },
  MediaConnection: {
    edges: "MediaEdge",
    nodes: "Media",
    pageInfo: "PageInfo",
  },
  MediaCoverImage: {
    color: "String",
    extraLarge: "String",
    large: "String",
    medium: "String",
  },
  MediaDataChangeNotification: {
    context: "String",
    createdAt: "Int",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    reason: "String",
    type: "NotificationType",
  },
  MediaDeletionNotification: {
    context: "String",
    createdAt: "Int",
    deletedMediaTitle: "String",
    id: "Int",
    reason: "String",
    type: "NotificationType",
  },
  MediaEdge: {
    characterName: "String",
    characterRole: "CharacterRole",
    characters: "Character",
    dubGroup: "String",
    favouriteOrder: "Int",
    id: "Int",
    isMainStudio: "Boolean",
    node: "Media",
    relationType: "MediaRelation",
    roleNotes: "String",
    staffRole: "String",
    voiceActorRoles: "StaffRoleType",
    voiceActors: "Staff",
  },
  MediaExternalLink: {
    color: "String",
    icon: "String",
    id: "Int",
    isDisabled: "Boolean",
    language: "String",
    notes: "String",
    site: "String",
    siteId: "Int",
    type: "ExternalLinkType",
    url: "String",
  },
  MediaList: {
    advancedScores: "Json",
    completedAt: "FuzzyDate",
    createdAt: "Int",
    customLists: "Json",
    hiddenFromStatusLists: "Boolean",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    notes: "String",
    priority: "Int",
    private: "Boolean",
    progress: "Int",
    progressVolumes: "Int",
    repeat: "Int",
    score: "Float",
    startedAt: "FuzzyDate",
    status: "MediaListStatus",
    updatedAt: "Int",
    user: "User",
    userId: "Int",
  },
  MediaListCollection: {
    customLists: "MediaList",
    hasNextChunk: "Boolean",
    lists: "MediaListGroup",
    statusLists: "MediaList",
    user: "User",
  },
  MediaListGroup: {
    entries: "MediaList",
    isCustomList: "Boolean",
    isSplitCompletedList: "Boolean",
    name: "String",
    status: "MediaListStatus",
  },
  MediaListOptions: {
    animeList: "MediaListTypeOptions",
    mangaList: "MediaListTypeOptions",
    rowOrder: "String",
    scoreFormat: "ScoreFormat",
    sharedTheme: "Json",
    sharedThemeEnabled: "Boolean",
    useLegacyLists: "Boolean",
  },
  MediaListTypeOptions: {
    advancedScoring: "String",
    advancedScoringEnabled: "Boolean",
    customLists: "String",
    sectionOrder: "String",
    splitCompletedSectionByFormat: "Boolean",
    theme: "Json",
  },
  MediaMergeNotification: {
    context: "String",
    createdAt: "Int",
    deletedMediaTitles: "String",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    reason: "String",
    type: "NotificationType",
  },
  MediaRank: {
    allTime: "Boolean",
    context: "String",
    format: "MediaFormat",
    id: "Int",
    rank: "Int",
    season: "MediaSeason",
    type: "MediaRankType",
    year: "Int",
  },
  MediaStats: {
    airingProgression: "AiringProgression",
    scoreDistribution: "ScoreDistribution",
    statusDistribution: "StatusDistribution",
  },
  MediaStreamingEpisode: {
    site: "String",
    thumbnail: "String",
    title: "String",
    url: "String",
  },
  MediaSubmission: {
    assignee: "User",
    changes: "String",
    characters: "MediaSubmissionComparison",
    createdAt: "Int",
    externalLinks: "MediaSubmissionComparison",
    id: "Int",
    locked: "Boolean",
    media: "Media",
    notes: "String",
    relations: "MediaEdge",
    source: "String",
    staff: "MediaSubmissionComparison",
    status: "SubmissionStatus",
    studios: "MediaSubmissionComparison",
    submission: "Media",
    submitter: "User",
    submitterStats: "Json",
  },
  MediaSubmissionComparison: {
    character: "MediaCharacter",
    externalLink: "MediaExternalLink",
    staff: "StaffEdge",
    studio: "StudioEdge",
    submission: "MediaSubmissionEdge",
  },
  MediaSubmissionEdge: {
    character: "Character",
    characterName: "String",
    characterRole: "CharacterRole",
    characterSubmission: "Character",
    dubGroup: "String",
    externalLink: "MediaExternalLink",
    id: "Int",
    isMain: "Boolean",
    media: "Media",
    roleNotes: "String",
    staff: "Staff",
    staffRole: "String",
    staffSubmission: "Staff",
    studio: "Studio",
    voiceActor: "Staff",
    voiceActorSubmission: "Staff",
  },
  MediaTag: {
    category: "String",
    description: "String",
    id: "Int",
    isAdult: "Boolean",
    isGeneralSpoiler: "Boolean",
    isMediaSpoiler: "Boolean",
    name: "String",
    rank: "Int",
    userId: "Int",
  },
  MediaTitle: {
    english: "String",
    native: "String",
    romaji: "String",
    userPreferred: "String",
  },
  MediaTrailer: {
    id: "String",
    site: "String",
    thumbnail: "String",
  },
  MediaTrend: {
    averageScore: "Int",
    date: "Int",
    episode: "Int",
    inProgress: "Int",
    media: "Media",
    mediaId: "Int",
    popularity: "Int",
    releasing: "Boolean",
    trending: "Int",
  },
  MediaTrendConnection: {
    edges: "MediaTrendEdge",
    nodes: "MediaTrend",
    pageInfo: "PageInfo",
  },
  MediaTrendEdge: {
    node: "MediaTrend",
  },
  MessageActivity: {
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    isLocked: "Boolean",
    isPrivate: "Boolean",
    isSubscribed: "Boolean",
    likeCount: "Int",
    likes: "User",
    message: "String",
    messenger: "User",
    messengerId: "Int",
    recipient: "User",
    recipientId: "Int",
    replies: "ActivityReply",
    replyCount: "Int",
    siteUrl: "String",
    type: "ActivityType",
  },
  ModAction: {
    createdAt: "Int",
    data: "String",
    id: "Int",
    mod: "User",
    objectId: "Int",
    objectType: "String",
    type: "ModActionType",
    user: "User",
  },
  Mutation: {
    DeleteActivity: "Deleted",
    DeleteActivityReply: "Deleted",
    DeleteCustomList: "Deleted",
    DeleteMediaListEntry: "Deleted",
    DeleteReview: "Deleted",
    DeleteThread: "Deleted",
    DeleteThreadComment: "Deleted",
    RateReview: "Review",
    SaveActivityReply: "ActivityReply",
    SaveListActivity: "ListActivity",
    SaveMediaListEntry: "MediaList",
    SaveMessageActivity: "MessageActivity",
    SaveRecommendation: "Recommendation",
    SaveReview: "Review",
    SaveTextActivity: "TextActivity",
    SaveThread: "Thread",
    SaveThreadComment: "ThreadComment",
    ToggleActivityPin: "ActivityUnion",
    ToggleActivitySubscription: "ActivityUnion",
    ToggleFavourite: "Favourites",
    ToggleFollow: "User",
    ToggleLike: "User",
    ToggleLikeV2: "LikeableUnion",
    ToggleThreadSubscription: "Thread",
    UpdateAniChartHighlights: "Json",
    UpdateAniChartSettings: "Json",
    UpdateFavouriteOrder: "Favourites",
    UpdateMediaListEntries: "MediaList",
    UpdateUser: "User",
  },
  NotificationOption: {
    enabled: "Boolean",
    type: "NotificationType",
  },
  Page: {
    activities: "ActivityUnion",
    activityReplies: "ActivityReply",
    airingSchedules: "AiringSchedule",
    characters: "Character",
    followers: "User",
    following: "User",
    likes: "User",
    media: "Media",
    mediaList: "MediaList",
    mediaTrends: "MediaTrend",
    notifications: "NotificationUnion",
    pageInfo: "PageInfo",
    recommendations: "Recommendation",
    reviews: "Review",
    staff: "Staff",
    studios: "Studio",
    threadComments: "ThreadComment",
    threads: "Thread",
    users: "User",
  },
  PageInfo: {
    currentPage: "Int",
    hasNextPage: "Boolean",
    lastPage: "Int",
    perPage: "Int",
    total: "Int",
  },
  ParsedMarkdown: {
    html: "String",
  },
  Query: {
    Activity: "ActivityUnion",
    ActivityReply: "ActivityReply",
    AiringSchedule: "AiringSchedule",
    AniChartUser: "AniChartUser",
    Character: "Character",
    ExternalLinkSourceCollection: "MediaExternalLink",
    Follower: "User",
    Following: "User",
    GenreCollection: "String",
    Like: "User",
    Markdown: "ParsedMarkdown",
    Media: "Media",
    MediaList: "MediaList",
    MediaListCollection: "MediaListCollection",
    MediaTagCollection: "MediaTag",
    MediaTrend: "MediaTrend",
    Notification: "NotificationUnion",
    Page: "Page",
    Recommendation: "Recommendation",
    Review: "Review",
    SiteStatistics: "SiteStatistics",
    Staff: "Staff",
    Studio: "Studio",
    Thread: "Thread",
    ThreadComment: "ThreadComment",
    User: "User",
    Viewer: "User",
  },
  Recommendation: {
    id: "Int",
    media: "Media",
    mediaRecommendation: "Media",
    rating: "Int",
    user: "User",
    userRating: "RecommendationRating",
  },
  RecommendationConnection: {
    edges: "RecommendationEdge",
    nodes: "Recommendation",
    pageInfo: "PageInfo",
  },
  RecommendationEdge: {
    node: "Recommendation",
  },
  RelatedMediaAdditionNotification: {
    context: "String",
    createdAt: "Int",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    type: "NotificationType",
  },
  Report: {
    cleared: "Boolean",
    createdAt: "Int",
    id: "Int",
    reason: "String",
    reported: "User",
    reporter: "User",
  },
  Review: {
    body: "String",
    createdAt: "Int",
    id: "Int",
    media: "Media",
    mediaId: "Int",
    mediaType: "MediaType",
    private: "Boolean",
    rating: "Int",
    ratingAmount: "Int",
    score: "Int",
    siteUrl: "String",
    summary: "String",
    updatedAt: "Int",
    user: "User",
    userId: "Int",
    userRating: "ReviewRating",
  },
  ReviewConnection: {
    edges: "ReviewEdge",
    nodes: "Review",
    pageInfo: "PageInfo",
  },
  ReviewEdge: {
    node: "Review",
  },
  RevisionHistory: {
    action: "RevisionHistoryAction",
    changes: "Json",
    character: "Character",
    createdAt: "Int",
    externalLink: "MediaExternalLink",
    id: "Int",
    media: "Media",
    staff: "Staff",
    studio: "Studio",
    user: "User",
  },
  ScoreDistribution: {
    amount: "Int",
    score: "Int",
  },
  SiteStatistics: {
    anime: "SiteTrendConnection",
    characters: "SiteTrendConnection",
    manga: "SiteTrendConnection",
    reviews: "SiteTrendConnection",
    staff: "SiteTrendConnection",
    studios: "SiteTrendConnection",
    users: "SiteTrendConnection",
  },
  SiteTrend: {
    change: "Int",
    count: "Int",
    date: "Int",
  },
  SiteTrendConnection: {
    edges: "SiteTrendEdge",
    nodes: "SiteTrend",
    pageInfo: "PageInfo",
  },
  SiteTrendEdge: {
    node: "SiteTrend",
  },
  Staff: {
    age: "Int",
    bloodType: "String",
    characterMedia: "MediaConnection",
    characters: "CharacterConnection",
    dateOfBirth: "FuzzyDate",
    dateOfDeath: "FuzzyDate",
    description: "String",
    favourites: "Int",
    gender: "String",
    homeTown: "String",
    id: "Int",
    image: "StaffImage",
    isFavourite: "Boolean",
    isFavouriteBlocked: "Boolean",
    language: "StaffLanguage",
    languageV2: "String",
    modNotes: "String",
    name: "StaffName",
    primaryOccupations: "String",
    siteUrl: "String",
    staff: "Staff",
    staffMedia: "MediaConnection",
    submissionNotes: "String",
    submissionStatus: "Int",
    submitter: "User",
    updatedAt: "Int",
    yearsActive: "Int",
  },
  StaffConnection: {
    edges: "StaffEdge",
    nodes: "Staff",
    pageInfo: "PageInfo",
  },
  StaffEdge: {
    favouriteOrder: "Int",
    id: "Int",
    node: "Staff",
    role: "String",
  },
  StaffImage: {
    large: "String",
    medium: "String",
  },
  StaffName: {
    alternative: "String",
    first: "String",
    full: "String",
    last: "String",
    middle: "String",
    native: "String",
    userPreferred: "String",
  },
  StaffRoleType: {
    dubGroup: "String",
    roleNotes: "String",
    voiceActor: "Staff",
  },
  StaffStats: {
    amount: "Int",
    meanScore: "Int",
    staff: "Staff",
    timeWatched: "Int",
  },
  StaffSubmission: {
    assignee: "User",
    createdAt: "Int",
    id: "Int",
    locked: "Boolean",
    notes: "String",
    source: "String",
    staff: "Staff",
    status: "SubmissionStatus",
    submission: "Staff",
    submitter: "User",
  },
  StatusDistribution: {
    amount: "Int",
    status: "MediaListStatus",
  },
  Studio: {
    favourites: "Int",
    id: "Int",
    isAnimationStudio: "Boolean",
    isFavourite: "Boolean",
    media: "MediaConnection",
    name: "String",
    siteUrl: "String",
  },
  StudioConnection: {
    edges: "StudioEdge",
    nodes: "Studio",
    pageInfo: "PageInfo",
  },
  StudioEdge: {
    favouriteOrder: "Int",
    id: "Int",
    isMain: "Boolean",
    node: "Studio",
  },
  StudioStats: {
    amount: "Int",
    meanScore: "Int",
    studio: "Studio",
    timeWatched: "Int",
  },
  TagStats: {
    amount: "Int",
    meanScore: "Int",
    tag: "MediaTag",
    timeWatched: "Int",
  },
  TextActivity: {
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    isLocked: "Boolean",
    isPinned: "Boolean",
    isSubscribed: "Boolean",
    likeCount: "Int",
    likes: "User",
    replies: "ActivityReply",
    replyCount: "Int",
    siteUrl: "String",
    text: "String",
    type: "ActivityType",
    user: "User",
    userId: "Int",
  },
  Thread: {
    body: "String",
    categories: "ThreadCategory",
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    isLocked: "Boolean",
    isSticky: "Boolean",
    isSubscribed: "Boolean",
    likeCount: "Int",
    likes: "User",
    mediaCategories: "Media",
    repliedAt: "Int",
    replyCommentId: "Int",
    replyCount: "Int",
    replyUser: "User",
    replyUserId: "Int",
    siteUrl: "String",
    title: "String",
    updatedAt: "Int",
    user: "User",
    userId: "Int",
    viewCount: "Int",
  },
  ThreadCategory: {
    id: "Int",
    name: "String",
  },
  ThreadComment: {
    childComments: "Json",
    comment: "String",
    createdAt: "Int",
    id: "Int",
    isLiked: "Boolean",
    isLocked: "Boolean",
    likeCount: "Int",
    likes: "User",
    siteUrl: "String",
    thread: "Thread",
    threadId: "Int",
    updatedAt: "Int",
    user: "User",
    userId: "Int",
  },
  ThreadCommentLikeNotification: {
    comment: "ThreadComment",
    commentId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    thread: "Thread",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ThreadCommentMentionNotification: {
    comment: "ThreadComment",
    commentId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    thread: "Thread",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ThreadCommentReplyNotification: {
    comment: "ThreadComment",
    commentId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    thread: "Thread",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ThreadCommentSubscribedNotification: {
    comment: "ThreadComment",
    commentId: "Int",
    context: "String",
    createdAt: "Int",
    id: "Int",
    thread: "Thread",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  ThreadLikeNotification: {
    comment: "ThreadComment",
    context: "String",
    createdAt: "Int",
    id: "Int",
    thread: "Thread",
    threadId: "Int",
    type: "NotificationType",
    user: "User",
    userId: "Int",
  },
  User: {
    about: "String",
    avatar: "UserAvatar",
    bannerImage: "String",
    bans: "Json",
    createdAt: "Int",
    donatorBadge: "String",
    donatorTier: "Int",
    favourites: "Favourites",
    id: "Int",
    isBlocked: "Boolean",
    isFollower: "Boolean",
    isFollowing: "Boolean",
    mediaListOptions: "MediaListOptions",
    moderatorRoles: "ModRole",
    moderatorStatus: "String",
    name: "String",
    options: "UserOptions",
    previousNames: "UserPreviousName",
    siteUrl: "String",
    statistics: "UserStatisticTypes",
    stats: "UserStats",
    unreadNotificationCount: "Int",
    updatedAt: "Int",
  },
  UserActivityHistory: {
    amount: "Int",
    date: "Int",
    level: "Int",
  },
  UserAvatar: {
    large: "String",
    medium: "String",
  },
  UserCountryStatistic: {
    chaptersRead: "Int",
    count: "Int",
    country: "CountryCode",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
  },
  UserFormatStatistic: {
    chaptersRead: "Int",
    count: "Int",
    format: "MediaFormat",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
  },
  UserGenreStatistic: {
    chaptersRead: "Int",
    count: "Int",
    genre: "String",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
  },
  UserLengthStatistic: {
    chaptersRead: "Int",
    count: "Int",
    length: "String",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
  },
  UserModData: {
    alts: "User",
    bans: "Json",
    counts: "Json",
    email: "String",
    ip: "Json",
    privacy: "Int",
  },
  UserOptions: {
    activityMergeTime: "Int",
    airingNotifications: "Boolean",
    disabledListActivity: "ListActivityOption",
    displayAdultContent: "Boolean",
    notificationOptions: "NotificationOption",
    profileColor: "String",
    restrictMessagesToFollowing: "Boolean",
    staffNameLanguage: "UserStaffNameLanguage",
    timezone: "String",
    titleLanguage: "UserTitleLanguage",
  },
  UserPreviousName: {
    createdAt: "Int",
    name: "String",
    updatedAt: "Int",
  },
  UserReleaseYearStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    releaseYear: "Int",
  },
  UserScoreStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    score: "Int",
  },
  UserStaffStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    staff: "Staff",
  },
  UserStartYearStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    startYear: "Int",
  },
  UserStatisticTypes: {
    anime: "UserStatistics",
    manga: "UserStatistics",
  },
  UserStatistics: {
    chaptersRead: "Int",
    count: "Int",
    countries: "UserCountryStatistic",
    episodesWatched: "Int",
    formats: "UserFormatStatistic",
    genres: "UserGenreStatistic",
    lengths: "UserLengthStatistic",
    meanScore: "Float",
    minutesWatched: "Int",
    releaseYears: "UserReleaseYearStatistic",
    scores: "UserScoreStatistic",
    staff: "UserStaffStatistic",
    standardDeviation: "Float",
    startYears: "UserStartYearStatistic",
    statuses: "UserStatusStatistic",
    studios: "UserStudioStatistic",
    tags: "UserTagStatistic",
    voiceActors: "UserVoiceActorStatistic",
    volumesRead: "Int",
  },
  UserStats: {
    activityHistory: "UserActivityHistory",
    animeListScores: "ListScoreStats",
    animeScoreDistribution: "ScoreDistribution",
    animeStatusDistribution: "StatusDistribution",
    chaptersRead: "Int",
    favouredActors: "StaffStats",
    favouredFormats: "FormatStats",
    favouredGenres: "GenreStats",
    favouredGenresOverview: "GenreStats",
    favouredStaff: "StaffStats",
    favouredStudios: "StudioStats",
    favouredTags: "TagStats",
    favouredYears: "YearStats",
    mangaListScores: "ListScoreStats",
    mangaScoreDistribution: "ScoreDistribution",
    mangaStatusDistribution: "StatusDistribution",
    watchedTime: "Int",
  },
  UserStatusStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    status: "MediaListStatus",
  },
  UserStudioStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    studio: "Studio",
  },
  UserTagStatistic: {
    chaptersRead: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    tag: "MediaTag",
  },
  UserVoiceActorStatistic: {
    chaptersRead: "Int",
    characterIds: "Int",
    count: "Int",
    meanScore: "Float",
    mediaIds: "Int",
    minutesWatched: "Int",
    voiceActor: "Staff",
  },
  YearStats: {
    amount: "Int",
    meanScore: "Int",
    year: "Int",
  },
  CountryCode: `scalar.CountryCode` as const,
  FuzzyDateInt: `scalar.FuzzyDateInt` as const,
  Json: `scalar.Json` as const,
  ID: `scalar.ID` as const,
};

export const Ops = {
  query: "Query" as const,
  mutation: "Mutation" as const,
};
