/* eslint-disable */

export const AllTypesProps: Record<string, any> = {
  Episodic: {
    episodes: {
      sort: "EpisodeSortOption",
    },
  },
  Media: {
    categories: {
      sort: "MediaCategorySortOption",
    },
    characters: {
      sort: "MediaCharacterSortOption",
    },
    description: {},
    mappings: {},
    myWikiSubmissions: {
      sort: "WikiSubmissionSortOption",
    },
    posts: {
      sort: "PostSortOption",
    },
    productions: {},
    quotes: {},
    reactions: {
      sort: "MediaReactionSortOption",
    },
    relationships: {},
    staff: {},
  },
  Unit: {
    description: {},
  },
  AccountMutations: {
    changePassword: {
      input: "AccountChangePasswordInput",
    },
    sendPasswordReset: {},
    update: {
      input: "AccountUpdateInput",
    },
  },
  Anime: {
    categories: {
      sort: "MediaCategorySortOption",
    },
    characters: {
      sort: "MediaCharacterSortOption",
    },
    description: {},
    episodes: {
      sort: "EpisodeSortOption",
    },
    mappings: {},
    myWikiSubmissions: {
      sort: "WikiSubmissionSortOption",
    },
    posts: {
      sort: "PostSortOption",
    },
    productions: {},
    quotes: {},
    reactions: {
      sort: "MediaReactionSortOption",
    },
    relationships: {},
    staff: {},
    streamingLinks: {},
  },
  AnimeMutations: {
    create: {
      input: "AnimeCreateInput",
    },
    delete: {
      input: "GenericDeleteInput",
    },
    update: {
      input: "AnimeUpdateInput",
    },
  },
  BlockMutations: {
    create: {
      input: "BlockCreateInput",
    },
    delete: {
      input: "BlockDeleteInput",
    },
  },
  Category: {
    children: {},
    description: {},
    title: {},
  },
  Chapter: {
    description: {},
  },
  Character: {
    description: {},
    media: {},
  },
  Comment: {
    likes: {
      sort: "CommentLikeSortOption",
    },
    replies: {
      sort: "CommentSortOption",
    },
  },
  Episode: {
    description: {},
  },
  EpisodeMutations: {
    create: {
      input: "EpisodeCreateInput",
    },
    delete: {
      input: "GenericDeleteInput",
    },
    update: {
      input: "EpisodeUpdateInput",
    },
  },
  FavoriteMutations: {
    create: {
      input: "FavoriteCreateInput",
    },
    delete: {
      input: "FavoriteDeleteInput",
    },
  },
  Franchise: {
    installments: {
      sort: "InstallmentSortOption",
    },
  },
  Image: {
    views: {},
  },
  Library: {
    all: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
      status: "LibraryEntryStatusEnum",
    },
    completed: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
    },
    current: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
    },
    dropped: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
    },
    onHold: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
    },
    planned: {
      mediaType: "MediaTypeEnum",
      sort: "LibraryEntrySortOption",
    },
    randomMedia: {
      mediaType: "MediaTypeEnum",
      status: "LibraryEntryStatusEnum",
    },
  },
  LibraryEntry: {
    events: {
      mediaTypes: "MediaTypeEnum",
    },
  },
  LibraryEntryMutations: {
    create: {
      input: "LibraryEntryCreateInput",
    },
    delete: {
      input: "GenericDeleteInput",
    },
    update: {
      input: "LibraryEntryUpdateInput",
    },
    updateProgressById: {
      input: "LibraryEntryUpdateProgressByIdInput",
    },
    updateProgressByMedia: {
      input: "LibraryEntryUpdateProgressByMediaInput",
    },
    updateRatingById: {
      input: "LibraryEntryUpdateRatingByIdInput",
    },
    updateRatingByMedia: {
      input: "LibraryEntryUpdateRatingByMediaInput",
    },
    updateStatusById: {
      input: "LibraryEntryUpdateStatusByIdInput",
    },
    updateStatusByMedia: {
      input: "LibraryEntryUpdateStatusByMediaInput",
    },
  },
  Manga: {
    categories: {
      sort: "MediaCategorySortOption",
    },
    chapter: {},
    chapters: {
      sort: "ChapterSortOption",
    },
    characters: {
      sort: "MediaCharacterSortOption",
    },
    description: {},
    mappings: {},
    myWikiSubmissions: {
      sort: "WikiSubmissionSortOption",
    },
    posts: {
      sort: "PostSortOption",
    },
    productions: {},
    quotes: {},
    reactions: {
      sort: "MediaReactionSortOption",
    },
    relationships: {},
    staff: {},
    volumes: {
      sort: "VolumeSortOption",
    },
  },
  MappingMutations: {
    create: {
      input: "MappingCreateInput",
    },
    delete: {
      input: "GenericDeleteInput",
    },
    update: {
      input: "MappingUpdateInput",
    },
  },
  MediaCharacter: {
    voices: {
      sort: "CharacterVoiceSortOption",
    },
  },
  MediaReaction: {
    likes: {
      sort: "MediaReactionVoteSortOption",
    },
  },
  MediaReactionMutations: {
    create: {
      input: "MediaReactionCreateInput",
    },
    delete: {
      input: "MediaReactionDeleteInput",
    },
    like: {
      input: "MediaReactionLikeInput",
    },
    unlike: {
      input: "MediaReactionUnlikeInput",
    },
  },
  Mutation: {
    accountCreate: {
      input: "AccountCreateInput",
    },
  },
  Person: {
    description: {},
    mediaStaff: {},
    voices: {},
  },
  Post: {
    comments: {
      sort: "CommentSortOption",
    },
    follows: {},
    likes: {
      sort: "PostLikeSortOption",
    },
  },
  PostMutations: {
    create: {
      input: "PostCreateInput",
    },
    lock: {
      input: "PostLockInput",
    },
    unlock: {
      input: "PostUnlockInput",
    },
  },
  ProMutations: {
    setDiscord: {},
    setMessage: {},
  },
  Profile: {
    comments: {},
    favorites: {},
    followers: {
      sort: "FollowSortOption",
    },
    following: {
      sort: "FollowSortOption",
    },
    libraryEvents: {
      kind: "LibraryEventKindEnum",
      sort: "LibraryEventSortOption",
    },
    mediaReactions: {
      sort: "MediaReactionSortOption",
    },
    posts: {
      sort: "PostSortOption",
    },
    reviews: {
      sort: "WikiSubmissionSortOption",
    },
    siteLinks: {},
    wikiSubmissions: {
      sort: "WikiSubmissionSortOption",
      statuses: "WikiSubmissionStatusEnum",
    },
  },
  ProfileLinkMutations: {
    create: {
      input: "ProfileLinkCreateInput",
    },
    delete: {
      input: "ProfileLinkDeleteInput",
    },
    update: {
      input: "ProfileLinkUpdateInput",
    },
  },
  ProfileMutations: {
    update: {
      input: "ProfileUpdateInput",
    },
  },
  Query: {
    anime: {},
    animeByStatus: {
      status: "ReleaseStatusEnum",
    },
    blocks: {},
    categories: {},
    findAnimeById: {},
    findAnimeBySlug: {},
    findCategoryById: {},
    findCategoryBySlug: {},
    findChapterById: {},
    findCharacterById: {},
    findCharacterBySlug: {},
    findLibraryEntryById: {},
    findLibraryEventById: {},
    findMangaById: {},
    findMangaBySlug: {},
    findMediaByIdAndType: {
      mediaType: "MediaTypeEnum",
    },
    findPersonById: {},
    findPersonBySlug: {},
    findPostById: {},
    findProfileById: {},
    findProfileBySlug: {},
    findReportById: {},
    findWikiSubmissionById: {},
    franchises: {},
    globalTrending: {
      mediaType: "MediaTypeEnum",
    },
    libraryEntriesByMedia: {
      mediaType: "MediaTypeEnum",
    },
    libraryEntriesByMediaType: {
      mediaType: "MediaTypeEnum",
    },
    localTrending: {
      mediaType: "MediaTypeEnum",
    },
    lookupMapping: {
      externalSite: "MappingExternalSiteEnum",
    },
    manga: {},
    mangaByStatus: {
      status: "ReleaseStatusEnum",
    },
    patrons: {},
    randomMedia: {
      ageRatings: "AgeRatingEnum",
      mediaType: "MediaTypeEnum",
    },
    reports: {},
    reportsByStatus: {
      statuses: "ReportStatusEnum",
    },
    searchAnimeByTitle: {},
    searchMangaByTitle: {},
    searchMediaByTitle: {
      mediaType: "MediaTypeEnum",
    },
    searchProfileByUsername: {},
    wikiSubmissionsByStatuses: {
      sort: "WikiSubmissionSortOption",
      statuses: "WikiSubmissionStatusEnum",
    },
  },
  Quote: {
    lines: {},
  },
  Review: {
    likes: {},
  },
  Streamer: {
    streamingLinks: {},
    videos: {},
  },
  TitlesList: {
    localized: {},
  },
  Volume: {
    chapters: {},
    description: {},
  },
  WikiSubmissionMutations: {
    createDraft: {
      input: "WikiSubmissionCreateDraftInput",
    },
    submitDraft: {
      input: "WikiSubmissionSubmitDraftInput",
    },
    updateDraft: {
      input: "WikiSubmissionUpdateDraftInput",
    },
  },
  AgeRatingEnum: "enum" as const,
  AnimeSubtypeEnum: "enum" as const,
  ChapterSortEnum: "enum" as const,
  CharacterRoleEnum: "enum" as const,
  CharacterVoiceSortEnum: "enum" as const,
  CommentLikeSortEnum: "enum" as const,
  CommentSortEnum: "enum" as const,
  EpisodeSortEnum: "enum" as const,
  ExternalIdentityProviderEnum: "enum" as const,
  FavoriteEnum: "enum" as const,
  FollowSortEnum: "enum" as const,
  InstallmentSortEnum: "enum" as const,
  InstallmentTagEnum: "enum" as const,
  LibraryEntrySortEnum: "enum" as const,
  LibraryEntryStatusEnum: "enum" as const,
  LibraryEventKindEnum: "enum" as const,
  LibraryEventSortEnum: "enum" as const,
  LockedReasonEnum: "enum" as const,
  MangaSubtypeEnum: "enum" as const,
  MappingExternalSiteEnum: "enum" as const,
  MappingItemEnum: "enum" as const,
  MediaCategorySortEnum: "enum" as const,
  MediaCharacterSortEnum: "enum" as const,
  MediaProductionRoleEnum: "enum" as const,
  MediaReactionSortEnum: "enum" as const,
  MediaReactionVoteSortEnum: "enum" as const,
  MediaRelationshipKindEnum: "enum" as const,
  MediaTypeEnum: "enum" as const,
  PostLikeSortEnum: "enum" as const,
  PostSortEnum: "enum" as const,
  ProTierEnum: "enum" as const,
  ProfileLinksSitesEnum: "enum" as const,
  RatingSystemEnum: "enum" as const,
  RecurringBillingServiceEnum: "enum" as const,
  ReleaseSeasonEnum: "enum" as const,
  ReleaseStatusEnum: "enum" as const,
  ReportReasonEnum: "enum" as const,
  ReportStatusEnum: "enum" as const,
  SfwFilterPreferenceEnum: "enum" as const,
  SitePermissionEnum: "enum" as const,
  SiteThemeEnum: "enum" as const,
  SortDirection: "enum" as const,
  TitleLanguagePreferenceEnum: "enum" as const,
  VolumeSortEnum: "enum" as const,
  WaifuOrHusbandoEnum: "enum" as const,
  WikiSubmissionSortEnum: "enum" as const,
  WikiSubmissionStatusEnum: "enum" as const,
  Date: `scalar.Date` as const,
  ISO8601Date: `scalar.ISO8601Date` as const,
  ISO8601DateTime: `scalar.ISO8601DateTime` as const,
  JSON: `scalar.JSON` as const,
  Map: `scalar.Map` as const,
  Upload: `scalar.Upload` as const,
  AccountChangePasswordInput: {},
  AccountCreateInput: {
    externalIdentity: "AccountExternalIdentityInput",
  },
  AccountExternalIdentityInput: {
    provider: "ExternalIdentityProviderEnum",
  },
  AccountUpdateInput: {
    preferredTitleLanguage: "TitleLanguagePreferenceEnum",
    ratingSystem: "RatingSystemEnum",
    sfwFilterPreference: "SfwFilterPreferenceEnum",
    siteTheme: "SiteThemeEnum",
  },
  AnimeCreateInput: {
    ageRating: "AgeRatingEnum",
    bannerImage: "Upload",
    description: "Map",
    endDate: "Date",
    posterImage: "Upload",
    startDate: "Date",
    titles: "TitlesListInput",
  },
  AnimeUpdateInput: {
    ageRating: "AgeRatingEnum",
    bannerImage: "Upload",
    description: "Map",
    endDate: "Date",
    posterImage: "Upload",
    startDate: "Date",
    titles: "TitlesListInput",
  },
  BlockCreateInput: {},
  BlockDeleteInput: {},
  ChapterSortOption: {
    direction: "SortDirection",
    on: "ChapterSortEnum",
  },
  CharacterVoiceSortOption: {
    direction: "SortDirection",
    on: "CharacterVoiceSortEnum",
  },
  CommentLikeSortOption: {
    direction: "SortDirection",
    on: "CommentLikeSortEnum",
  },
  CommentSortOption: {
    direction: "SortDirection",
    on: "CommentSortEnum",
  },
  EpisodeCreateInput: {
    description: "Map",
    mediaType: "MediaTypeEnum",
    releasedAt: "Date",
    thumbnailImage: "Upload",
    titles: "TitlesListInput",
  },
  EpisodeSortOption: {
    direction: "SortDirection",
    on: "EpisodeSortEnum",
  },
  EpisodeUpdateInput: {
    description: "Map",
    releasedAt: "Date",
    thumbnailImage: "Upload",
    titles: "TitlesListInput",
  },
  FavoriteCreateInput: {
    type: "FavoriteEnum",
  },
  FavoriteDeleteInput: {},
  FollowSortOption: {
    direction: "SortDirection",
    on: "FollowSortEnum",
  },
  GenericDeleteInput: {},
  InstallmentSortOption: {
    direction: "SortDirection",
    on: "InstallmentSortEnum",
  },
  LibraryEntryCreateInput: {
    finishedAt: "ISO8601DateTime",
    mediaType: "MediaTypeEnum",
    startedAt: "ISO8601DateTime",
    status: "LibraryEntryStatusEnum",
  },
  LibraryEntrySortOption: {
    direction: "SortDirection",
    on: "LibraryEntrySortEnum",
  },
  LibraryEntryUpdateInput: {
    finishedAt: "ISO8601DateTime",
    startedAt: "ISO8601DateTime",
    status: "LibraryEntryStatusEnum",
  },
  LibraryEntryUpdateProgressByIdInput: {},
  LibraryEntryUpdateProgressByMediaInput: {
    mediaType: "MediaTypeEnum",
  },
  LibraryEntryUpdateRatingByIdInput: {},
  LibraryEntryUpdateRatingByMediaInput: {
    mediaType: "MediaTypeEnum",
  },
  LibraryEntryUpdateStatusByIdInput: {
    status: "LibraryEntryStatusEnum",
  },
  LibraryEntryUpdateStatusByMediaInput: {
    mediaType: "MediaTypeEnum",
    status: "LibraryEntryStatusEnum",
  },
  LibraryEventSortOption: {
    direction: "SortDirection",
    on: "LibraryEventSortEnum",
  },
  MappingCreateInput: {
    externalSite: "MappingExternalSiteEnum",
    itemType: "MappingItemEnum",
  },
  MappingUpdateInput: {
    externalSite: "MappingExternalSiteEnum",
    itemType: "MappingItemEnum",
  },
  MediaCategorySortOption: {
    direction: "SortDirection",
    on: "MediaCategorySortEnum",
  },
  MediaCharacterSortOption: {
    direction: "SortDirection",
    on: "MediaCharacterSortEnum",
  },
  MediaReactionCreateInput: {},
  MediaReactionDeleteInput: {},
  MediaReactionLikeInput: {},
  MediaReactionSortOption: {
    direction: "SortDirection",
    on: "MediaReactionSortEnum",
  },
  MediaReactionUnlikeInput: {},
  MediaReactionVoteSortOption: {
    direction: "SortDirection",
    on: "MediaReactionVoteSortEnum",
  },
  PostCreateInput: {
    mediaType: "MediaTypeEnum",
  },
  PostLikeSortOption: {
    direction: "SortDirection",
    on: "PostLikeSortEnum",
  },
  PostLockInput: {
    lockedReason: "LockedReasonEnum",
  },
  PostSortOption: {
    direction: "SortDirection",
    on: "PostSortEnum",
  },
  PostUnlockInput: {},
  ProfileLinkCreateInput: {
    profileLinkSite: "ProfileLinksSitesEnum",
  },
  ProfileLinkDeleteInput: {
    profileLink: "ProfileLinksSitesEnum",
  },
  ProfileLinkUpdateInput: {
    profileLinkSite: "ProfileLinksSitesEnum",
  },
  ProfileUpdateInput: {
    birthday: "Date",
    waifuOrHusbando: "WaifuOrHusbandoEnum",
  },
  TitlesListInput: {
    localized: "Map",
  },
  VolumeSortOption: {
    direction: "SortDirection",
    on: "VolumeSortEnum",
  },
  WikiSubmissionCreateDraftInput: {
    data: "JSON",
  },
  WikiSubmissionSortOption: {
    direction: "SortDirection",
    on: "WikiSubmissionSortEnum",
  },
  WikiSubmissionSubmitDraftInput: {
    data: "JSON",
  },
  WikiSubmissionUpdateDraftInput: {
    data: "JSON",
  },
  ID: `scalar.ID` as const,
};

export const ReturnTypes: Record<string, any> = {
  oneOf: {},
  AmountConsumed: {
    "...on AnimeAmountConsumed": "AnimeAmountConsumed",
    "...on MangaAmountConsumed": "MangaAmountConsumed",
    completed: "Int",
    id: "ID",
    media: "Int",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    units: "Int",
  },
  CategoryBreakdown: {
    "...on AnimeCategoryBreakdown": "AnimeCategoryBreakdown",
    "...on MangaCategoryBreakdown": "MangaCategoryBreakdown",
    categories: "Map",
    id: "ID",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    total: "Int",
  },
  Episodic: {
    "...on Anime": "Anime",
    episodeCount: "Int",
    episodeLength: "Int",
    episodes: "EpisodeConnection",
    totalLength: "Int",
  },
  Error: {
    "...on GenericError": "GenericError",
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
    "...on ValidationError": "ValidationError",
    code: "String",
    message: "String",
    path: "String",
  },
  Media: {
    "...on Anime": "Anime",
    "...on Manga": "Manga",
    ageRating: "AgeRatingEnum",
    ageRatingGuide: "String",
    averageRating: "Float",
    averageRatingRank: "Int",
    bannerImage: "Image",
    categories: "CategoryConnection",
    characters: "MediaCharacterConnection",
    description: "Map",
    endDate: "Date",
    favoritesCount: "Int",
    id: "ID",
    mappings: "MappingConnection",
    myLibraryEntry: "LibraryEntry",
    myWikiSubmissions: "WikiSubmissionConnection",
    nextRelease: "ISO8601DateTime",
    originCountries: "String",
    originLanguages: "String",
    originalLocale: "String",
    posterImage: "Image",
    posts: "PostConnection",
    productions: "MediaProductionConnection",
    quotes: "QuoteConnection",
    reactions: "MediaReactionConnection",
    relationships: "MediaRelationshipConnection",
    sfw: "Boolean",
    slug: "String",
    staff: "MediaStaffConnection",
    startDate: "Date",
    status: "ReleaseStatusEnum",
    tba: "String",
    titles: "TitlesList",
    type: "String",
    userCount: "Int",
    userCountRank: "Int",
  },
  Streamable: {
    "...on StreamingLink": "StreamingLink",
    "...on Video": "Video",
    dubs: "String",
    regions: "String",
    streamer: "Streamer",
    subs: "String",
  },
  Unit: {
    "...on Chapter": "Chapter",
    "...on Episode": "Episode",
    "...on Volume": "Volume",
    description: "Map",
    id: "ID",
    number: "Int",
    thumbnail: "Image",
    titles: "TitlesList",
  },
  WithTimestamps: {
    "...on Account": "Account",
    "...on Anime": "Anime",
    "...on Block": "Block",
    "...on Category": "Category",
    "...on Chapter": "Chapter",
    "...on Character": "Character",
    "...on CharacterVoice": "CharacterVoice",
    "...on Comment": "Comment",
    "...on Episode": "Episode",
    "...on Favorite": "Favorite",
    "...on Franchise": "Franchise",
    "...on Installment": "Installment",
    "...on LibraryEntry": "LibraryEntry",
    "...on LibraryEvent": "LibraryEvent",
    "...on Manga": "Manga",
    "...on Mapping": "Mapping",
    "...on MediaCharacter": "MediaCharacter",
    "...on MediaProduction": "MediaProduction",
    "...on MediaReaction": "MediaReaction",
    "...on MediaRelationship": "MediaRelationship",
    "...on MediaStaff": "MediaStaff",
    "...on Person": "Person",
    "...on Post": "Post",
    "...on ProSubscription": "ProSubscription",
    "...on Producer": "Producer",
    "...on Profile": "Profile",
    "...on ProfileLinkSite": "ProfileLinkSite",
    "...on Quote": "Quote",
    "...on QuoteLine": "QuoteLine",
    "...on Report": "Report",
    "...on Review": "Review",
    "...on SiteLink": "SiteLink",
    "...on Streamer": "Streamer",
    "...on StreamingLink": "StreamingLink",
    "...on Video": "Video",
    "...on Volume": "Volume",
    "...on WikiSubmission": "WikiSubmission",
    createdAt: "ISO8601DateTime",
    updatedAt: "ISO8601DateTime",
  },
  AccountChangePasswordErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on ValidationError": "ValidationError",
  },
  AccountCreateErrorsUnion: {
    "...on ValidationError": "ValidationError",
  },
  AccountUpdateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  BlockCreateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  BlockDeleteErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  FavoriteCreateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  FavoriteDeleteErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  FavoriteItemUnion: {
    "...on Anime": "Anime",
    "...on Character": "Character",
    "...on Manga": "Manga",
    "...on Person": "Person",
  },
  MappingItemUnion: {
    "...on Anime": "Anime",
    "...on Category": "Category",
    "...on Character": "Character",
    "...on Episode": "Episode",
    "...on Manga": "Manga",
    "...on Person": "Person",
    "...on Producer": "Producer",
  },
  MediaReactionCreateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
    "...on ValidationError": "ValidationError",
  },
  MediaReactionDeleteErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  MediaReactionLikeErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  MediaReactionUnlikeErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  ProfileLinkCreateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
    "...on ValidationError": "ValidationError",
  },
  ProfileLinkDeleteErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  ProfileLinkUpdateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
    "...on ValidationError": "ValidationError",
  },
  ProfileUpdateErrorsUnion: {
    "...on NotAuthenticatedError": "NotAuthenticatedError",
    "...on NotAuthorizedError": "NotAuthorizedError",
    "...on NotFoundError": "NotFoundError",
  },
  ReportItemUnion: {
    "...on Comment": "Comment",
    "...on MediaReaction": "MediaReaction",
    "...on Post": "Post",
    "...on Review": "Review",
  },
  Account: {
    country: "String",
    createdAt: "ISO8601DateTime",
    email: "String",
    enabledFeatures: "String",
    facebookId: "String",
    id: "ID",
    language: "String",
    maxProStreak: "Int",
    proSubscription: "ProSubscription",
    profile: "Profile",
    ratingSystem: "RatingSystemEnum",
    sfwFilter: "Boolean",
    sfwFilterPreference: "SfwFilterPreferenceEnum",
    sitePermissions: "SitePermissionEnum",
    timeZone: "String",
    titleLanguagePreference: "TitleLanguagePreferenceEnum",
    twitterId: "String",
    updatedAt: "ISO8601DateTime",
  },
  AccountChangePasswordPayload: {
    errors: "AccountChangePasswordErrorsUnion",
    result: "Account",
  },
  AccountCreatePayload: {
    errors: "AccountCreateErrorsUnion",
    result: "Account",
  },
  AccountMutations: {
    changePassword: "AccountChangePasswordPayload",
    sendPasswordReset: "AccountSendPasswordResetPayload",
    update: "AccountUpdatePayload",
  },
  AccountSendPasswordResetPayload: {
    email: "String",
  },
  AccountUpdatePayload: {
    errors: "AccountUpdateErrorsUnion",
    result: "Account",
  },
  Anime: {
    ageRating: "AgeRatingEnum",
    ageRatingGuide: "String",
    averageRating: "Float",
    averageRatingRank: "Int",
    bannerImage: "Image",
    categories: "CategoryConnection",
    characters: "MediaCharacterConnection",
    createdAt: "ISO8601DateTime",
    description: "Map",
    endDate: "Date",
    episodeCount: "Int",
    episodeLength: "Int",
    episodes: "EpisodeConnection",
    favoritesCount: "Int",
    id: "ID",
    mappings: "MappingConnection",
    myLibraryEntry: "LibraryEntry",
    myWikiSubmissions: "WikiSubmissionConnection",
    nextRelease: "ISO8601DateTime",
    originCountries: "String",
    originLanguages: "String",
    originalLocale: "String",
    posterImage: "Image",
    posts: "PostConnection",
    productions: "MediaProductionConnection",
    quotes: "QuoteConnection",
    reactions: "MediaReactionConnection",
    relationships: "MediaRelationshipConnection",
    season: "ReleaseSeasonEnum",
    sfw: "Boolean",
    slug: "String",
    staff: "MediaStaffConnection",
    startDate: "Date",
    status: "ReleaseStatusEnum",
    streamingLinks: "StreamingLinkConnection",
    subtype: "AnimeSubtypeEnum",
    tba: "String",
    titles: "TitlesList",
    totalLength: "Int",
    type: "String",
    updatedAt: "ISO8601DateTime",
    userCount: "Int",
    userCountRank: "Int",
    youtubeTrailerVideoId: "String",
  },
  AnimeAmountConsumed: {
    completed: "Int",
    id: "ID",
    media: "Int",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    time: "Int",
    units: "Int",
  },
  AnimeCategoryBreakdown: {
    categories: "Map",
    id: "ID",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    total: "Int",
  },
  AnimeConnection: {
    edges: "AnimeEdge",
    nodes: "Anime",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  AnimeCreatePayload: {
    anime: "Anime",
    errors: "Error",
  },
  AnimeDeletePayload: {
    anime: "GenericDelete",
    errors: "Error",
  },
  AnimeEdge: {
    cursor: "String",
    node: "Anime",
  },
  AnimeMutations: {
    create: "AnimeCreatePayload",
    delete: "AnimeDeletePayload",
    update: "AnimeUpdatePayload",
  },
  AnimeUpdatePayload: {
    anime: "Anime",
    errors: "Error",
  },
  Block: {
    blockedUser: "Profile",
    createdAt: "ISO8601DateTime",
    id: "ID",
    updatedAt: "ISO8601DateTime",
    user: "Profile",
  },
  BlockConnection: {
    edges: "BlockEdge",
    nodes: "Block",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  BlockCreatePayload: {
    errors: "BlockCreateErrorsUnion",
    result: "Block",
  },
  BlockDeletePayload: {
    errors: "BlockDeleteErrorsUnion",
    result: "Block",
  },
  BlockEdge: {
    cursor: "String",
    node: "Block",
  },
  BlockMutations: {
    create: "BlockCreatePayload",
    delete: "BlockDeletePayload",
  },
  Category: {
    children: "CategoryConnection",
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    isNsfw: "Boolean",
    parent: "Category",
    root: "Category",
    slug: "String",
    title: "Map",
    updatedAt: "ISO8601DateTime",
  },
  CategoryConnection: {
    edges: "CategoryEdge",
    nodes: "Category",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  CategoryEdge: {
    cursor: "String",
    node: "Category",
  },
  Chapter: {
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    length: "Int",
    manga: "Manga",
    number: "Int",
    releasedAt: "ISO8601Date",
    thumbnail: "Image",
    titles: "TitlesList",
    updatedAt: "ISO8601DateTime",
    volume: "Volume",
  },
  ChapterConnection: {
    edges: "ChapterEdge",
    nodes: "Chapter",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  ChapterEdge: {
    cursor: "String",
    node: "Chapter",
  },
  Character: {
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    image: "Image",
    media: "MediaCharacterConnection",
    names: "TitlesList",
    primaryMedia: "Media",
    slug: "String",
    updatedAt: "ISO8601DateTime",
  },
  CharacterVoice: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    licensor: "Producer",
    locale: "String",
    mediaCharacter: "MediaCharacter",
    person: "Person",
    updatedAt: "ISO8601DateTime",
  },
  CharacterVoiceConnection: {
    edges: "CharacterVoiceEdge",
    nodes: "CharacterVoice",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  CharacterVoiceEdge: {
    cursor: "String",
    node: "CharacterVoice",
  },
  Comment: {
    author: "Profile",
    content: "String",
    contentFormatted: "String",
    createdAt: "ISO8601DateTime",
    id: "ID",
    likes: "ProfileConnection",
    parent: "Comment",
    post: "Post",
    replies: "CommentConnection",
    updatedAt: "ISO8601DateTime",
  },
  CommentConnection: {
    edges: "CommentEdge",
    nodes: "Comment",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  CommentEdge: {
    cursor: "String",
    node: "Comment",
  },
  Episode: {
    anime: "Anime",
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    length: "Int",
    number: "Int",
    releasedAt: "ISO8601DateTime",
    thumbnail: "Image",
    titles: "TitlesList",
    updatedAt: "ISO8601DateTime",
  },
  EpisodeConnection: {
    edges: "EpisodeEdge",
    nodes: "Episode",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  EpisodeCreatePayload: {
    episode: "Episode",
    errors: "Error",
  },
  EpisodeDeletePayload: {
    episode: "GenericDelete",
    errors: "Error",
  },
  EpisodeEdge: {
    cursor: "String",
    node: "Episode",
  },
  EpisodeMutations: {
    create: "EpisodeCreatePayload",
    delete: "EpisodeDeletePayload",
    update: "EpisodeUpdatePayload",
  },
  EpisodeUpdatePayload: {
    episode: "Episode",
    errors: "Error",
  },
  Favorite: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    item: "FavoriteItemUnion",
    updatedAt: "ISO8601DateTime",
    user: "Profile",
  },
  FavoriteConnection: {
    edges: "FavoriteEdge",
    nodes: "Favorite",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  FavoriteCreatePayload: {
    errors: "FavoriteCreateErrorsUnion",
    result: "Favorite",
  },
  FavoriteDeletePayload: {
    errors: "FavoriteDeleteErrorsUnion",
    result: "Favorite",
  },
  FavoriteEdge: {
    cursor: "String",
    node: "Favorite",
  },
  FavoriteMutations: {
    create: "FavoriteCreatePayload",
    delete: "FavoriteDeletePayload",
  },
  Franchise: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    installments: "InstallmentConnection",
    titles: "TitlesList",
    updatedAt: "ISO8601DateTime",
  },
  FranchiseConnection: {
    edges: "FranchiseEdge",
    nodes: "Franchise",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  FranchiseEdge: {
    cursor: "String",
    node: "Franchise",
  },
  GenericDelete: {
    id: "ID",
  },
  GenericError: {
    code: "String",
    message: "String",
    path: "String",
  },
  Image: {
    blurhash: "String",
    original: "ImageView",
    views: "ImageView",
  },
  ImageView: {
    height: "Int",
    name: "String",
    url: "String",
    width: "Int",
  },
  Installment: {
    alternativeOrder: "Int",
    createdAt: "ISO8601DateTime",
    franchise: "Franchise",
    id: "ID",
    media: "Media",
    releaseOrder: "Int",
    tag: "InstallmentTagEnum",
    updatedAt: "ISO8601DateTime",
  },
  InstallmentConnection: {
    edges: "InstallmentEdge",
    nodes: "Installment",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  InstallmentEdge: {
    cursor: "String",
    node: "Installment",
  },
  Library: {
    all: "LibraryEntryConnection",
    completed: "LibraryEntryConnection",
    current: "LibraryEntryConnection",
    dropped: "LibraryEntryConnection",
    onHold: "LibraryEntryConnection",
    planned: "LibraryEntryConnection",
    randomMedia: "Media",
  },
  LibraryEntry: {
    createdAt: "ISO8601DateTime",
    events: "LibraryEventConnection",
    finishedAt: "ISO8601DateTime",
    id: "ID",
    lastUnit: "Unit",
    media: "Media",
    nextUnit: "Unit",
    notes: "String",
    nsfw: "Boolean",
    private: "Boolean",
    progress: "Int",
    progressedAt: "ISO8601DateTime",
    rating: "Int",
    reaction: "MediaReaction",
    reconsumeCount: "Int",
    reconsuming: "Boolean",
    startedAt: "ISO8601DateTime",
    status: "LibraryEntryStatusEnum",
    updatedAt: "ISO8601DateTime",
    user: "Profile",
    volumesOwned: "Int",
  },
  LibraryEntryConnection: {
    edges: "LibraryEntryEdge",
    nodes: "LibraryEntry",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  LibraryEntryCreatePayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryDeletePayload: {
    errors: "Error",
    libraryEntry: "GenericDelete",
  },
  LibraryEntryEdge: {
    cursor: "String",
    node: "LibraryEntry",
  },
  LibraryEntryMutations: {
    create: "LibraryEntryCreatePayload",
    delete: "LibraryEntryDeletePayload",
    update: "LibraryEntryUpdatePayload",
    updateProgressById: "LibraryEntryUpdateProgressByIdPayload",
    updateProgressByMedia: "LibraryEntryUpdateProgressByMediaPayload",
    updateRatingById: "LibraryEntryUpdateRatingByIdPayload",
    updateRatingByMedia: "LibraryEntryUpdateRatingByMediaPayload",
    updateStatusById: "LibraryEntryUpdateStatusByIdPayload",
    updateStatusByMedia: "LibraryEntryUpdateStatusByMediaPayload",
  },
  LibraryEntryUpdatePayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateProgressByIdPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateProgressByMediaPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateRatingByIdPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateRatingByMediaPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateStatusByIdPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEntryUpdateStatusByMediaPayload: {
    errors: "Error",
    libraryEntry: "LibraryEntry",
  },
  LibraryEvent: {
    changedData: "Map",
    createdAt: "ISO8601DateTime",
    id: "ID",
    kind: "LibraryEventKindEnum",
    libraryEntry: "LibraryEntry",
    media: "Media",
    updatedAt: "ISO8601DateTime",
    user: "Profile",
  },
  LibraryEventConnection: {
    edges: "LibraryEventEdge",
    nodes: "LibraryEvent",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  LibraryEventEdge: {
    cursor: "String",
    node: "LibraryEvent",
  },
  Manga: {
    ageRating: "AgeRatingEnum",
    ageRatingGuide: "String",
    averageRating: "Float",
    averageRatingRank: "Int",
    bannerImage: "Image",
    categories: "CategoryConnection",
    chapter: "Chapter",
    chapterCount: "Int",
    chapterCountGuess: "Int",
    chapters: "ChapterConnection",
    characters: "MediaCharacterConnection",
    createdAt: "ISO8601DateTime",
    description: "Map",
    endDate: "Date",
    favoritesCount: "Int",
    id: "ID",
    mappings: "MappingConnection",
    myLibraryEntry: "LibraryEntry",
    myWikiSubmissions: "WikiSubmissionConnection",
    nextRelease: "ISO8601DateTime",
    originCountries: "String",
    originLanguages: "String",
    originalLocale: "String",
    posterImage: "Image",
    posts: "PostConnection",
    productions: "MediaProductionConnection",
    quotes: "QuoteConnection",
    reactions: "MediaReactionConnection",
    relationships: "MediaRelationshipConnection",
    sfw: "Boolean",
    slug: "String",
    staff: "MediaStaffConnection",
    startDate: "Date",
    status: "ReleaseStatusEnum",
    subtype: "MangaSubtypeEnum",
    tba: "String",
    titles: "TitlesList",
    type: "String",
    updatedAt: "ISO8601DateTime",
    userCount: "Int",
    userCountRank: "Int",
    volumeCount: "Int",
    volumes: "VolumeConnection",
  },
  MangaAmountConsumed: {
    completed: "Int",
    id: "ID",
    media: "Int",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    units: "Int",
  },
  MangaCategoryBreakdown: {
    categories: "Map",
    id: "ID",
    profile: "Profile",
    recalculatedAt: "ISO8601Date",
    total: "Int",
  },
  MangaConnection: {
    edges: "MangaEdge",
    nodes: "Manga",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MangaEdge: {
    cursor: "String",
    node: "Manga",
  },
  Mapping: {
    createdAt: "ISO8601DateTime",
    externalId: "ID",
    externalSite: "MappingExternalSiteEnum",
    id: "ID",
    item: "MappingItemUnion",
    updatedAt: "ISO8601DateTime",
  },
  MappingConnection: {
    edges: "MappingEdge",
    nodes: "Mapping",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MappingCreatePayload: {
    errors: "Error",
    mapping: "Mapping",
  },
  MappingDeletePayload: {
    errors: "Error",
    mapping: "GenericDelete",
  },
  MappingEdge: {
    cursor: "String",
    node: "Mapping",
  },
  MappingMutations: {
    create: "MappingCreatePayload",
    delete: "MappingDeletePayload",
    update: "MappingUpdatePayload",
  },
  MappingUpdatePayload: {
    errors: "Error",
    mapping: "Mapping",
  },
  MediaCharacter: {
    character: "Character",
    createdAt: "ISO8601DateTime",
    id: "ID",
    media: "Media",
    role: "CharacterRoleEnum",
    updatedAt: "ISO8601DateTime",
    voices: "CharacterVoiceConnection",
  },
  MediaCharacterConnection: {
    edges: "MediaCharacterEdge",
    nodes: "MediaCharacter",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MediaCharacterEdge: {
    cursor: "String",
    node: "MediaCharacter",
  },
  MediaConnection: {
    edges: "MediaEdge",
    nodes: "Media",
    pageInfo: "PageInfo",
  },
  MediaEdge: {
    cursor: "String",
    node: "Media",
  },
  MediaProduction: {
    company: "Producer",
    createdAt: "ISO8601DateTime",
    id: "ID",
    media: "Media",
    role: "MediaProductionRoleEnum",
    updatedAt: "ISO8601DateTime",
  },
  MediaProductionConnection: {
    edges: "MediaProductionEdge",
    nodes: "MediaProduction",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MediaProductionEdge: {
    cursor: "String",
    node: "MediaProduction",
  },
  MediaReaction: {
    author: "Profile",
    createdAt: "ISO8601DateTime",
    hasLiked: "Boolean",
    id: "ID",
    libraryEntry: "LibraryEntry",
    likes: "ProfileConnection",
    media: "Media",
    progress: "Int",
    reaction: "String",
    updatedAt: "ISO8601DateTime",
  },
  MediaReactionConnection: {
    edges: "MediaReactionEdge",
    nodes: "MediaReaction",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MediaReactionCreatePayload: {
    errors: "MediaReactionCreateErrorsUnion",
    result: "MediaReaction",
  },
  MediaReactionDeletePayload: {
    errors: "MediaReactionDeleteErrorsUnion",
    result: "MediaReaction",
  },
  MediaReactionEdge: {
    cursor: "String",
    node: "MediaReaction",
  },
  MediaReactionLikePayload: {
    errors: "MediaReactionLikeErrorsUnion",
    result: "MediaReaction",
  },
  MediaReactionMutations: {
    create: "MediaReactionCreatePayload",
    delete: "MediaReactionDeletePayload",
    like: "MediaReactionLikePayload",
    unlike: "MediaReactionUnlikePayload",
  },
  MediaReactionUnlikePayload: {
    errors: "MediaReactionUnlikeErrorsUnion",
    result: "MediaReaction",
  },
  MediaRelationship: {
    createdAt: "ISO8601DateTime",
    destination: "Media",
    kind: "MediaRelationshipKindEnum",
    source: "Media",
    updatedAt: "ISO8601DateTime",
  },
  MediaRelationshipConnection: {
    edges: "MediaRelationshipEdge",
    nodes: "MediaRelationship",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MediaRelationshipEdge: {
    cursor: "String",
    node: "MediaRelationship",
  },
  MediaStaff: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    media: "Media",
    person: "Person",
    role: "String",
    updatedAt: "ISO8601DateTime",
  },
  MediaStaffConnection: {
    edges: "MediaStaffEdge",
    nodes: "MediaStaff",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  MediaStaffEdge: {
    cursor: "String",
    node: "MediaStaff",
  },
  Mutation: {
    account: "AccountMutations",
    accountCreate: "AccountCreatePayload",
    anime: "AnimeMutations",
    block: "BlockMutations",
    episode: "EpisodeMutations",
    favorite: "FavoriteMutations",
    libraryEntry: "LibraryEntryMutations",
    mapping: "MappingMutations",
    mediaReaction: "MediaReactionMutations",
    post: "PostMutations",
    pro: "ProMutations",
    profile: "ProfileMutations",
    profileLink: "ProfileLinkMutations",
    wikiSubmission: "WikiSubmissionMutations",
  },
  NotAuthenticatedError: {
    code: "String",
    message: "String",
    path: "String",
  },
  NotAuthorizedError: {
    action: "String",
    code: "String",
    message: "String",
    path: "String",
  },
  NotFoundError: {
    code: "String",
    message: "String",
    path: "String",
  },
  PageInfo: {
    endCursor: "String",
    hasNextPage: "Boolean",
    hasPreviousPage: "Boolean",
    startCursor: "String",
  },
  Person: {
    birthday: "Date",
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    image: "Image",
    mediaStaff: "MediaStaffConnection",
    name: "String",
    names: "TitlesList",
    slug: "String",
    updatedAt: "ISO8601DateTime",
    voices: "CharacterVoiceConnection",
  },
  Post: {
    author: "Profile",
    comments: "CommentConnection",
    content: "String",
    contentFormatted: "String",
    createdAt: "ISO8601DateTime",
    follows: "ProfileConnection",
    id: "ID",
    isNsfw: "Boolean",
    isSpoiler: "Boolean",
    likes: "ProfileConnection",
    lockedAt: "ISO8601DateTime",
    lockedBy: "Profile",
    lockedReason: "LockedReasonEnum",
    media: "Media",
    targetProfile: "Profile",
    updatedAt: "ISO8601DateTime",
  },
  PostConnection: {
    edges: "PostEdge",
    nodes: "Post",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  PostCreatePayload: {
    errors: "Error",
    post: "Post",
  },
  PostEdge: {
    cursor: "String",
    node: "Post",
  },
  PostLockPayload: {
    errors: "Error",
    post: "Post",
  },
  PostMutations: {
    create: "PostCreatePayload",
    lock: "PostLockPayload",
    unlock: "PostUnlockPayload",
  },
  PostUnlockPayload: {
    errors: "Error",
    post: "Post",
  },
  ProMutations: {
    setDiscord: "ProSetDiscordPayload",
    setMessage: "ProSetMessagePayload",
    unsubscribe: "ProUnsubscribePayload",
  },
  ProSetDiscordPayload: {
    discord: "String",
  },
  ProSetMessagePayload: {
    message: "String",
  },
  ProSubscription: {
    account: "Account",
    billingService: "RecurringBillingServiceEnum",
    createdAt: "ISO8601DateTime",
    tier: "ProTierEnum",
    updatedAt: "ISO8601DateTime",
  },
  ProUnsubscribePayload: {
    expiresAt: "ISO8601DateTime",
  },
  Producer: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    name: "String",
    updatedAt: "ISO8601DateTime",
  },
  Profile: {
    about: "String",
    avatarImage: "Image",
    bannerImage: "Image",
    birthday: "ISO8601Date",
    comments: "CommentConnection",
    createdAt: "ISO8601DateTime",
    favorites: "FavoriteConnection",
    followers: "ProfileConnection",
    following: "ProfileConnection",
    gender: "String",
    id: "ID",
    library: "Library",
    libraryEvents: "LibraryEventConnection",
    location: "String",
    mediaReactions: "MediaReactionConnection",
    name: "String",
    pinnedPost: "Post",
    posts: "PostConnection",
    proMessage: "String",
    proTier: "ProTierEnum",
    reviews: "ReviewConnection",
    siteLinks: "SiteLinkConnection",
    slug: "String",
    stats: "ProfileStats",
    updatedAt: "ISO8601DateTime",
    url: "String",
    waifu: "Character",
    waifuOrHusbando: "String",
    wikiSubmissions: "WikiSubmissionConnection",
  },
  ProfileConnection: {
    edges: "ProfileEdge",
    nodes: "Profile",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  ProfileEdge: {
    cursor: "String",
    node: "Profile",
  },
  ProfileLinkCreatePayload: {
    errors: "ProfileLinkCreateErrorsUnion",
    result: "SiteLink",
  },
  ProfileLinkDeletePayload: {
    errors: "ProfileLinkDeleteErrorsUnion",
    result: "SiteLink",
  },
  ProfileLinkMutations: {
    create: "ProfileLinkCreatePayload",
    delete: "ProfileLinkDeletePayload",
    update: "ProfileLinkUpdatePayload",
  },
  ProfileLinkSite: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    name: "String",
    updatedAt: "ISO8601DateTime",
    validateFind: "String",
    validateReplace: "String",
  },
  ProfileLinkUpdatePayload: {
    errors: "ProfileLinkUpdateErrorsUnion",
    result: "SiteLink",
  },
  ProfileMutations: {
    update: "ProfileUpdatePayload",
  },
  ProfileStats: {
    animeAmountConsumed: "AnimeAmountConsumed",
    animeCategoryBreakdown: "AnimeCategoryBreakdown",
    mangaAmountConsumed: "MangaAmountConsumed",
    mangaCategoryBreakdown: "MangaCategoryBreakdown",
  },
  ProfileUpdatePayload: {
    errors: "ProfileUpdateErrorsUnion",
    result: "Profile",
  },
  Query: {
    anime: "AnimeConnection",
    animeByStatus: "AnimeConnection",
    blocks: "BlockConnection",
    categories: "CategoryConnection",
    currentAccount: "Account",
    currentProfile: "Profile",
    findAnimeById: "Anime",
    findAnimeBySlug: "Anime",
    findCategoryById: "Category",
    findCategoryBySlug: "Category",
    findChapterById: "Chapter",
    findCharacterById: "Character",
    findCharacterBySlug: "Character",
    findLibraryEntryById: "LibraryEntry",
    findLibraryEventById: "LibraryEvent",
    findMangaById: "Manga",
    findMangaBySlug: "Manga",
    findMediaByIdAndType: "Media",
    findPersonById: "Person",
    findPersonBySlug: "Person",
    findPostById: "Post",
    findProfileById: "Profile",
    findProfileBySlug: "Profile",
    findReportById: "Report",
    findWikiSubmissionById: "WikiSubmission",
    franchises: "FranchiseConnection",
    globalTrending: "MediaConnection",
    libraryEntriesByMedia: "LibraryEntryConnection",
    libraryEntriesByMediaType: "LibraryEntryConnection",
    localTrending: "MediaConnection",
    lookupMapping: "MappingItemUnion",
    manga: "MangaConnection",
    mangaByStatus: "MangaConnection",
    patrons: "ProfileConnection",
    randomMedia: "Media",
    reports: "ReportConnection",
    reportsByStatus: "ReportConnection",
    searchAnimeByTitle: "AnimeConnection",
    searchMangaByTitle: "MangaConnection",
    searchMediaByTitle: "MediaConnection",
    searchProfileByUsername: "ProfileConnection",
    session: "Session",
    wikiSubmissionsByStatuses: "WikiSubmissionConnection",
  },
  Quote: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    lines: "QuoteLineConnection",
    media: "Media",
    updatedAt: "ISO8601DateTime",
  },
  QuoteConnection: {
    edges: "QuoteEdge",
    nodes: "Quote",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  QuoteEdge: {
    cursor: "String",
    node: "Quote",
  },
  QuoteLine: {
    character: "Character",
    content: "String",
    createdAt: "ISO8601DateTime",
    id: "ID",
    quote: "Quote",
    updatedAt: "ISO8601DateTime",
  },
  QuoteLineConnection: {
    edges: "QuoteLineEdge",
    nodes: "QuoteLine",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  QuoteLineEdge: {
    cursor: "String",
    node: "QuoteLine",
  },
  Report: {
    createdAt: "ISO8601DateTime",
    explanation: "String",
    id: "ID",
    moderator: "Profile",
    naughty: "ReportItemUnion",
    reason: "ReportReasonEnum",
    reporter: "Profile",
    status: "ReportStatusEnum",
    updatedAt: "ISO8601DateTime",
  },
  ReportConnection: {
    edges: "ReportEdge",
    nodes: "Report",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  ReportEdge: {
    cursor: "String",
    node: "Report",
  },
  Review: {
    author: "Profile",
    content: "String",
    createdAt: "ISO8601DateTime",
    formattedContent: "String",
    id: "ID",
    isSpoiler: "Boolean",
    libraryEntry: "LibraryEntry",
    likes: "ProfileConnection",
    media: "Media",
    progress: "Int",
    rating: "Int",
    source: "String",
    updatedAt: "ISO8601DateTime",
  },
  ReviewConnection: {
    edges: "ReviewEdge",
    nodes: "Review",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  ReviewEdge: {
    cursor: "String",
    node: "Review",
  },
  Session: {
    account: "Account",
    noltToken: "String",
    profile: "Profile",
  },
  SiteLink: {
    author: "Profile",
    createdAt: "ISO8601DateTime",
    id: "ID",
    site: "ProfileLinkSite",
    updatedAt: "ISO8601DateTime",
    url: "String",
  },
  SiteLinkConnection: {
    edges: "SiteLinkEdge",
    nodes: "SiteLink",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  SiteLinkEdge: {
    cursor: "String",
    node: "SiteLink",
  },
  Streamer: {
    createdAt: "ISO8601DateTime",
    id: "ID",
    siteName: "String",
    streamingLinks: "StreamingLinkConnection",
    updatedAt: "ISO8601DateTime",
    videos: "VideoConnection",
  },
  StreamingLink: {
    createdAt: "ISO8601DateTime",
    dubs: "String",
    id: "ID",
    media: "Media",
    regions: "String",
    streamer: "Streamer",
    subs: "String",
    updatedAt: "ISO8601DateTime",
    url: "String",
  },
  StreamingLinkConnection: {
    edges: "StreamingLinkEdge",
    nodes: "StreamingLink",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  StreamingLinkEdge: {
    cursor: "String",
    node: "StreamingLink",
  },
  TitlesList: {
    alternatives: "String",
    canonical: "String",
    canonicalLocale: "String",
    localized: "Map",
    original: "String",
    originalLocale: "String",
    preferred: "String",
    romanized: "String",
    romanizedLocale: "String",
    translated: "String",
    translatedLocale: "String",
  },
  ValidationError: {
    code: "String",
    message: "String",
    path: "String",
  },
  Video: {
    createdAt: "ISO8601DateTime",
    dubs: "String",
    episode: "Episode",
    id: "ID",
    regions: "String",
    streamer: "Streamer",
    subs: "String",
    updatedAt: "ISO8601DateTime",
    url: "String",
  },
  VideoConnection: {
    edges: "VideoEdge",
    nodes: "Video",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  VideoEdge: {
    cursor: "String",
    node: "Video",
  },
  Volume: {
    chapters: "ChapterConnection",
    chaptersCount: "Int",
    createdAt: "ISO8601DateTime",
    description: "Map",
    id: "ID",
    isbn: "String",
    manga: "Manga",
    number: "Int",
    published: "ISO8601Date",
    thumbnail: "Image",
    titles: "TitlesList",
    updatedAt: "ISO8601DateTime",
  },
  VolumeConnection: {
    edges: "VolumeEdge",
    nodes: "Volume",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  VolumeEdge: {
    cursor: "String",
    node: "Volume",
  },
  WikiSubmission: {
    author: "Profile",
    createdAt: "ISO8601DateTime",
    data: "JSON",
    id: "ID",
    notes: "String",
    status: "WikiSubmissionStatusEnum",
    title: "String",
    updatedAt: "ISO8601DateTime",
  },
  WikiSubmissionConnection: {
    edges: "WikiSubmissionEdge",
    nodes: "WikiSubmission",
    pageInfo: "PageInfo",
    totalCount: "Int",
  },
  WikiSubmissionCreateDraftPayload: {
    errors: "Error",
    wikiSubmission: "WikiSubmission",
  },
  WikiSubmissionEdge: {
    cursor: "String",
    node: "WikiSubmission",
  },
  WikiSubmissionMutations: {
    createDraft: "WikiSubmissionCreateDraftPayload",
    submitDraft: "WikiSubmissionSubmitDraftPayload",
    updateDraft: "WikiSubmissionUpdateDraftPayload",
  },
  WikiSubmissionSubmitDraftPayload: {
    errors: "Error",
    wikiSubmission: "WikiSubmission",
  },
  WikiSubmissionUpdateDraftPayload: {
    errors: "Error",
    wikiSubmission: "WikiSubmission",
  },
  Date: `scalar.Date` as const,
  ISO8601Date: `scalar.ISO8601Date` as const,
  ISO8601DateTime: `scalar.ISO8601DateTime` as const,
  JSON: `scalar.JSON` as const,
  Map: `scalar.Map` as const,
  Upload: `scalar.Upload` as const,
  ID: `scalar.ID` as const,
};

export const Ops = {
  query: "Query" as const,
  mutation: "Mutation" as const,
};
